package com.telerikacademy.tms.commands.enums;

public enum CommandType {
    CREATEPERSON,
    SHOWALLPEOPLE,
    SHOWPERSONACTIVITY,
    CREATETEAM,
    SHOWALLTEAMS,
    SHOWTEAMACTIVITY,
    ADDPERSONTOTEAM,
    SHOWALLTEAMMEMBERS,
    CREATEBOARDINTEAM,
    SHOWALLTEAMBOARDS,
    SHOWBOARDACTIVITY,
    CREATETASKINBOARD,
    CHANGESTORY,
    CHANGEBUG,
    CHANGEFEEDBACK,
    ASSIGNTASK,
    UNASSIGNTASK,
    ADDCOMMENT,
    LISTALLTASKS,
    LISTALLBUGS,
    LISTALLSTORIES,
    LISTALLFEEDBACKS,
    LISTTASKSWITHASSIGNEE;
}
